---
# In development environment a user with same name as your system user will be created
development_user: "{{ lookup('env', 'USER') }}"

system_administrators:
  - name: daniel
    ssh_key: '{{ inventory_dir }}/../files/keys/daniel.pub'
    state: present
  - name: enrico
    ssh_key: '{{ inventory_dir }}/../files/keys/enrico.pub'
    state: present
  - name: cesar
    ssh_key: '{{ inventory_dir }}/../files/keys/cesar.pub'
    state: present

developers: []

# Let's Encrypt conf
certificate_authority_email:

# Set 'development_environment' to "true" to skip SSL and nginx tasks
development_environment: true
