---
odoo_provisioning_version: v0.1.0

odoo_user: odoo
odoo_edition: oca
# TODO: We need separate the community and the core modules, by now are the same list
odoo_core_modules: "account,account_analytic_default,account_asset,account_bank_statement_import,account_banking_mandate,account_banking_pain_base,account_banking_sepa_credit_transfer,account_banking_sepa_direct_debit,account_cancel,account_due_list,account_financial_report,account_invoicing,account_lock_date_update,account_move_line_tax_editable,account_payment_mode,account_payment_order,account_payment_partner,account_payment_return,account_payment_return_import,account_payment_return_import_sepa_pain,account_tax_balance,analytic,auth_brute_force,auth_crypt,auth_signup,base,base_address_city,base_automation,base_bank_from_iban,base_iban,base_import,base_location,base_location_geonames_import,base_setup,base_technical_features,base_vat,base_vat_autocomplete,board,calendar,contacts,contract,contract_sale_invoicing,contract_variable_qty_timesheet,contract_variable_quantity,date_range,decimal_precision,document,document_url,fetchmail,http_routing,iap,l10n_es,l10n_es_account_asset,l10n_es_account_bank_statement_import_n43,l10n_es_account_invoice_sequence,l10n_es_aeat,l10n_es_aeat_mod111,l10n_es_aeat_mod115,l10n_es_aeat_mod303,l10n_es_aeat_mod349,l10n_es_aeat_mod390,l10n_es_mis_report,l10n_es_partner,l10n_es_toponyms,l10n_es_vat_book,mail_tracking,mail_tracking_mailgun,mass_editing,mis_builder,module_auto_update,password_security,payment,payment_transfer,phone_validation,product,product_margin,report_xlsx,utm,web,web_decimal_numpad_dot,web_diagram,web_editor,web_favicon,web_no_bubble,web_planner,web_responsive,web_searchbar_full_width,web_settings_dashboard,web_tour,web_widget_color"
odoo_community_modules: "account,account_analytic_default,account_asset,account_bank_statement_import,account_banking_mandate,account_banking_pain_base,account_banking_sepa_credit_transfer,account_banking_sepa_direct_debit,account_cancel,account_due_list,account_financial_report,account_invoicing,account_lock_date_update,account_move_line_tax_editable,account_payment_mode,account_payment_order,account_payment_partner,account_payment_return,account_payment_return_import,account_payment_return_import_sepa_pain,account_tax_balance,analytic,auth_brute_force,auth_crypt,auth_signup,base,base_address_city,base_automation,base_bank_from_iban,base_iban,base_import,base_location,base_location_geonames_import,base_setup,base_technical_features,base_vat,base_vat_autocomplete,board,calendar,contacts,contract,contract_sale_invoicing,contract_variable_qty_timesheet,contract_variable_quantity,date_range,decimal_precision,document,document_url,fetchmail,http_routing,iap,l10n_es,l10n_es_account_asset,l10n_es_account_bank_statement_import_n43,l10n_es_account_invoice_sequence,l10n_es_aeat,l10n_es_aeat_mod111,l10n_es_aeat_mod115,l10n_es_aeat_mod303,l10n_es_aeat_mod349,l10n_es_aeat_mod390,l10n_es_mis_report,l10n_es_partner,l10n_es_toponyms,l10n_es_vat_book,mail_tracking,mail_tracking_mailgun,mass_editing,mis_builder,module_auto_update,password_security,payment,payment_transfer,phone_validation,product,product_margin,report_xlsx,utm,web,web_decimal_numpad_dot,web_diagram,web_editor,web_favicon,web_no_bubble,web_planner,web_responsive,web_searchbar_full_width,web_settings_dashboard,web_tour,web_widget_color"

odoo_db_name: LaBorda

ansible_python_interpreter: "/usr/bin/python3"

backups_role_enabled: false

# Nginx configuration
nginx_configs:
  upstream:
    - upstream odoo { server 127.0.0.1:8069; }

nginx_sites:
  odoo:
    - |
      listen 80;
      server_name {{ inventory_hostname }};
      rewrite ^(.*)$ https://$host$1 permanent;
  odoo.ssl:
    - |
      listen 443 ssl;
      ssl_certificate /etc/letsencrypt/live/{{ inventory_hostname }}/fullchain.pem;
      ssl_certificate_key /etc/letsencrypt/live/{{ inventory_hostname }}/privkey.pem;
      include /etc/letsencrypt/options-ssl-nginx.conf;
      ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
      server_name {{ inventory_hostname }};
      proxy_read_timeout 720s;
      proxy_connect_timeout 720s;
      proxy_send_timeout 720s;
      proxy_set_header X-Forwarded-Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Real-IP $remote_addr;
      ssl on;
      access_log /var/log/nginx/odoo.access.log;
      error_log /var/log/nginx/odoo.error.log;
      location / {
        proxy_redirect off;
        proxy_pass http://odoo;
      }
      gzip_types text/css text/less text/plain text/xml application/xml application/json application/javascript;
      gzip on;
